#![cfg(feature = "r255")]

use consensus::engine::ConsensusEngine;
use vrf::RealRistrettoVrf;
use vrf::VrfBackend;
use sha2::{Digest, Sha256};

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{:02x}", b)).collect::<Vec<_>>().join("")
}

#[test]
fn ristretto_crossnode_argmin_selection() {
    // Create three engines using ed25519 keypairs (generated by engine) and attach Ristretto VRF backends.
    let mut e1 = ConsensusEngine::new_with_rng(vec![], Box::new(RealRistrettoVrf::generate()), 1000);
    let mut e2 = ConsensusEngine::new_with_rng(vec![], Box::new(RealRistrettoVrf::generate()), 1000);
    let mut e3 = ConsensusEngine::new_with_rng(vec![], Box::new(RealRistrettoVrf::generate()), 1000);

    // Build validators from the engines' signing public keys (ed25519 public bytes)
    let pk1 = e1.keypair.public.to_bytes().to_vec();
    let pk2 = e2.keypair.public.to_bytes().to_vec();
    let pk3 = e3.keypair.public.to_bytes().to_vec();
    let validators = vec![pk1.clone(), pk2.clone(), pk3.clone()];

    // Attach the same validators list to all engines so they agree on mapping
    e1.validators = validators.clone();
    e2.validators = validators.clone();
    e3.validators = validators.clone();

    let parent = [0u8;32];

    for h in 1..50u64 {
        // Build shared seed: parent || height
        let mut seed = Vec::new();
        seed.extend_from_slice(&parent);
        seed.extend_from_slice(&h.to_be_bytes());

        // Collect all VRF outputs (raw bytes) for this seed from each validator
        let outs = vec![
            (0usize, e1.vrf.prove(&seed).expect("vrf1").1),
            (1usize, e2.vrf.prove(&seed).expect("vrf2").1),
            (2usize, e3.vrf.prove(&seed).expect("vrf3").1),
        ];

        // For each out compute H(out) and pick the minimal digest (lexicographic compare)
        let mut min_idx: Option<usize> = None;
        let mut min_digest: Option<Vec<u8>> = None;
        for (i, out) in &outs {
            let mut hsh = Sha256::new();
            hsh.update(out);
            let digest = hsh.finalize().to_vec();
            if min_digest.is_none() || digest < min_digest.clone().unwrap() {
                min_digest = Some(digest.clone());
                min_idx = Some(*i);
            }
        }

        let winner = min_idx.expect("we must have a winner");
        // winner is the validator index in 'validators' chosen by argmin(H(vrf_out))
        // Ensure exactly one winner (argmin picks exactly one in our code)
        assert!(winner <= 2);

        // For extra assurance, ensure the chosen validator's public key is one of the validator list
        let winner_pub = &validators[winner];
        assert!(validators.iter().any(|v| v == winner_pub));

        // optional: sanity print on failures (uncomment to debug)
        // println!("height {} winner idx {} pub {}", h, winner, hex(&winner_pub));

        // We don't assert on am_i_proposer() here because that method is local-only.
        // This test simulates the global argmin selection you'd perform after collecting proofs.
    }
}
